apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    lb-svc-attachment.kube-system.kubernetes.io/logical_switch: ovn-vpc-external-network
    ovn.kubernetes.io/attachmentprovider: ovn-vpc-external-network.kube-system
