helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.15.3
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true
    valuesInline:
      crds:
        enabled: true

resources:
  - namespace.yaml
