/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/mNi-Cloud/operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeComponents implements ComponentInterface
type FakeComponents struct {
	Fake *FakeApiV1alpha1
	ns   string
}

var componentsResource = v1alpha1.SchemeGroupVersion.WithResource("components")

var componentsKind = v1alpha1.SchemeGroupVersion.WithKind("Component")

// Get takes name of the component, and returns the corresponding component object, and an error if there is any.
func (c *FakeComponents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Component, err error) {
	emptyResult := &v1alpha1.Component{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(componentsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Component), err
}

// List takes label and field selectors, and returns the list of Components that match those selectors.
func (c *FakeComponents) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ComponentList, err error) {
	emptyResult := &v1alpha1.ComponentList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(componentsResource, componentsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ComponentList{ListMeta: obj.(*v1alpha1.ComponentList).ListMeta}
	for _, item := range obj.(*v1alpha1.ComponentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested components.
func (c *FakeComponents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(componentsResource, c.ns, opts))

}

// Create takes the representation of a component and creates it.  Returns the server's representation of the component, and an error, if there is any.
func (c *FakeComponents) Create(ctx context.Context, component *v1alpha1.Component, opts v1.CreateOptions) (result *v1alpha1.Component, err error) {
	emptyResult := &v1alpha1.Component{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(componentsResource, c.ns, component, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Component), err
}

// Update takes the representation of a component and updates it. Returns the server's representation of the component, and an error, if there is any.
func (c *FakeComponents) Update(ctx context.Context, component *v1alpha1.Component, opts v1.UpdateOptions) (result *v1alpha1.Component, err error) {
	emptyResult := &v1alpha1.Component{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(componentsResource, c.ns, component, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Component), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeComponents) UpdateStatus(ctx context.Context, component *v1alpha1.Component, opts v1.UpdateOptions) (result *v1alpha1.Component, err error) {
	emptyResult := &v1alpha1.Component{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(componentsResource, "status", c.ns, component, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Component), err
}

// Delete takes name of the component and deletes it. Returns an error if one occurs.
func (c *FakeComponents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(componentsResource, c.ns, name, opts), &v1alpha1.Component{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeComponents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(componentsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ComponentList{})
	return err
}

// Patch applies the patch and returns the patched component.
func (c *FakeComponents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Component, err error) {
	emptyResult := &v1alpha1.Component{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(componentsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Component), err
}
