apiVersion: operator.mnicloud.jp/v1alpha1
kind: Component
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: component-sample
spec:
  # TODO(user): Add fields here
