apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mni-mc
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/proxy-buffers-size: "16k"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "32k"
spec:
  rules:
    - host: hostname.replacethis
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mni-mc-main
                port:
                  number: 80
  tls:
    - hosts:
        - hostname.replacethis
      secretName: mni-mc-cert
