helmCharts:
  - name: mni-cloud
    repo: https://charts.mnicloud.jp
    version: 0.2.4
    releaseName: mni-cloud
    namespace: mni-cloud
    valuesInline:
      frontends:
        - name: mni-mc-main
          replicas: 1
          image: "ghcr.io/mni-cloud/mc-main:main"
          args: []
          env: 
            - name: "NEXTAUTH_URL"
              value: "url.replacethis"
            - name: "NEXTAUTH_SECRET"
              value: "secret.replacethis"
            - name: "NEXT_PUBLIC_API_DOMAIN"
              value: "mni-mc-api"
            - name: "NEXT_PUBLIC_DASHBOARD_DOMAIN"
              value: "mni-mc-dashboard"
            - name: "NEXT_PUBLIC_VPC_DOMAIN"
              value: "mni-mc-vpc"
            - name: "NEXT_PUBLIC_VM_DOMAIN"
              value: "mni-mc-vm"
            - name: "NEXT_PUBLIC_BS_DOMAIN"
              value: "mni-mc-bs"
            - name: "NEXT_PUBLIC_CTR_DOMAIN"
              value: "mni-mc-ctr"
          containerPort: 3000

        - name: mni-mc-api
          replicas: 1
          image: "ghcr.io/mni-cloud/mc-api:main"
          args: []
          env: 
            - name: "NEXT_PUBLIC_MNI_VPC_ENDPOINT"
              value: "http://vpc.mni-cloud.svc/v1alpha1"
            - name: "NEXT_PUBLIC_MNI_VM_ENDPOINT"
              value: "http://vm.mni-cloud.svc/v1alpha1"
            - name: "NEXT_PUBLIC_MNI_CTR_ENDPOINT"
              value: "http://ctr.mni-cloud.svc/v1alpha1"
            - name: "NEXT_PUBLIC_MNI_BS_ENDPOINT"
              value: "http://bs.mni-cloud.svc/v1alpha1"
            - name: "NEXTAUTH_URL"
              value: "url.replacethis"
            - name: "NEXTAUTH_SECRET"
              value: "secret.replacethis"
            - name: "KEYCLOAK_ID"
              value: "keycloakid.replacethis"
            - name: "KEYCLOAK_SECRET"
              value: "keycloaksecret.replacethis"
            - name: "KEYCLOAK_ISSUER"
              value: "keycloakurl.replacethis"
          containerPort: 3000

        - name: mni-mc-dashboard
          replicas: 1
          image: "ghcr.io/mni-cloud/mc-dashboard:main"
          args: []
          containerPort: 3000

        - name: mni-mc-vpc
          replicas: 1
          image: "ghcr.io/mni-cloud/mc-vpc:main"
          args: []
          containerPort: 3000

        - name: mni-mc-vm
          replicas: 1
          image: "ghcr.io/mni-cloud/mc-vm:main"
          args: []
          containerPort: 3000

        - name: mni-mc-bs
          replicas: 1
          image: "ghcr.io/mni-cloud/mc-bs:main"
          args: []
          containerPort: 3000

        - name: mni-mc-ctr
          replicas: 1
          image: "ghcr.io/mni-cloud/mc-ctr:main"
          args: []
          containerPort: 3000

resources:
  - ingress.yaml

namespace: mni-cloud